# Generated by Django 5.0.3 on 2024-05-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField()),
                ('icon', models.CharField(max_length=100)),
                ('key_menu', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('order_menu', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('type_menu', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
    ]
